添加windows对于tts的支持，优化通知 added support for windows tts, and enhanced information notifier
StoneMoe/wolf pull request #2
Opened 2022-01-03 04:55 UTC by aalberrty

+windows对于tts的支持
+在服务器开启后，通知用户可以连接到的ip（内网）

+support for windows tts
+after server start-up, tells user connectable internal ip

2022-01-03 17:00 UTC, StoneMoe requested changes

2022-01-03 17:00 UTC, StoneMoe commented on main.py
> +try:
需要考虑一下异常处理，和connect timeout

2022-01-03 17:00 UTC, StoneMoe commented on main.py
> +    print(f"狼人杀服务器启动成功！可以通过在浏览器内输入{ip}来加入游戏")
多interface环境下，这个提示文案并不准确

2022-01-03 17:00 UTC, StoneMoe commented on utils.py
> +    elif platform.system() == "windows":
此处的runAndWait是否会block到tts播放完毕？
macOS下该函数逻辑为“开始播放并立即返回”，并不会blocking到TTS音频播放完毕才返回
这里需要统一一下say函数在各platform下的行为

2022-01-03 17:01 UTC, StoneMoe commented
另外需要更新一下`.gitignore`，把`.DS_Store`删掉

2022-01-05 07:28 UTC, StoneMoe requested changes
Sorry，获取IP信息这块我之前理解有误，之前的是没问题的\
`main.py`可以回滚到上一个版本\
TTS这块麻烦依旧按照之前的建议确认一下，谢谢。

2022-01-05 17:03 UTC, aalberrty commented on utils.py
> +    elif platform.system() == "windows":
我想到的办法就是新开一个线程运行tts模块

2022-01-06 04:20 UTC, StoneMoe commented
测了一下，问题稍微有点多，我直接上手改了。

谢谢PR。

2022-01-06 04:21 UTC, merged